spring.datasource.url=jdbc:postgresql://localhost:5432/ssehub
spring.datasource.username=postgres
spring.datasource.password=Sanjaya@2525
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a7593c27e0c704bb4e35db0b59b5d234a7171f253715f20f04c601db54eb683e30f14fa76e4c3b6f28cf085b376ee2e8
jwt.expirationMs=86400000

server.port=8080

# Frontend URL (used in email links)
app.frontend.url=http://localhost:5173

# Gmail SMTP Configuration
# Use ONE Gmail account with App Password for all outgoing emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_GMAIL_ADDRESS@gmail.com
spring.mail.password=YOUR_16_CHAR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
